apiVersion: v1
kind: Service
metadata:
  name: httpd-service-nautilus
spec:
  type: NodePort
  selector:
    app: httpd-app-nautilus
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment-nautilus
  labels:
    app: httpd-app-nautilus
spec:
  replicas: 4
  selector:
    matchLabels:
      app: httpd-app-nautilus
  template:
    metadata:
      labels:
        app: httpd-app-nautilus
    spec:
      containers:
        - name: httpd-container-nautilus
          image: gcr.io/global-song-354109/gketask:latest
          ports:
            - containerPort: 80
