steps:
  # build the container image
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/global-song-354109/gketask:latest", "."]
  # push container image
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/global-song-354109/gketask:latest"]
  # deploy container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=app_trial1.yaml
  - --location=us-central1-c
  - --cluster=harir-cluster-trial
  - --namespace=$BRANCH_NAME
  - --app=httpd-app-nautilus
  - --expose=80
options:
  logging: CLOUD_LOGGING_ONLY
