steps:
  # build the container image
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/global-song-354109/gketask:dev", "."]
  # push container image
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/global-song-354109/gketask:dev"]
  # deploy container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  id: deploy-gke
  args:
  - run
  - --filename=app.yaml
  - --location=us-central1-c
  - --cluster=harir-cluster-trial
  - --namespace=$BRANCH_NAME
- name: 'gcr.io/cloud-builders/kubectl'
  id: kubectl-rollout-update
  args:
  - rollout
  - restart
  - deployment
  - hello-world
  - --namespace=dev
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=harir-cluster-trial'
  waitFor:
    - deploy-gke
options:
  logging: CLOUD_LOGGING_ONLY
